import { useEffect, useRef, useState } from "react";
import Chart from "chart.js/auto";
import clsx from "clsx";

interface DoughnutChartProps {
  data: any;
  formatLabel: (record: any) => React.ReactNode;
  className?: string;
  volume?: string;
}

// ⚠️ Generated by Cursor AI

// Define color palette for different data items
const COLOR_PALETTE = ["#C3C1DC", "#ACA9CA", "#8A87AA"];

export default function DoughnutChart({
  data,
  formatLabel,
  className,
  volume
}: DoughnutChartProps) {
  const chartRef = useRef<HTMLCanvasElement>(null);
  const chartInstance = useRef<Chart | null>(null);
  const [selectedIndex, setSelectedIndex] = useState(0);

  // Create chart only when data changes
  useEffect(() => {
    if (!chartRef.current) return;

    // Destroy existing chart instance
    if (chartInstance.current) {
      chartInstance.current.destroy();
    }

    const ctx = chartRef.current.getContext("2d");
    if (!ctx) return;

    // Check if data is empty or undefined
    const hasData = data && data.length > 0;

    // Check if all values are 0
    const allValuesZero =
      hasData && data.every((item: any) => item.value === 0);

    // Prepare chart data with initial colors (no selected state)
    const chartData = {
      labels: hasData ? data.map((item: any) => item.label) : [""],
      datasets: [
        {
          data: allValuesZero
            ? [1] // Show full circle when all values are 0
            : hasData
            ? data.map((item: any) => item.value)
            : [1],
          backgroundColor: allValuesZero
            ? ["rgba(195, 193, 220, 0.3)"] // Use #C3C1DC when all values are 0
            : hasData
            ? data.map((_item: any, index: number) => {
                // Use different color from palette for each data item
                return _item.value === 0
                  ? "rgba(195, 193, 220, 0.3)"
                  : COLOR_PALETTE[index % COLOR_PALETTE.length];
              })
            : ["rgba(195, 193, 220, 0.3)"], // Empty state color
          // borderWidth: 2,
          // borderColor: "#000", // Background color for gaps
          cutout: "78%" // Doughnut chart inner radius
        }
      ]
    };

    // Create chart configuration
    const config = {
      type: "doughnut" as const,
      data: chartData,
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false // Hide legend
          },
          tooltip: {
            enabled: false // Disable default tooltip
          }
        },
        onClick: (_event: any, elements: any[]) => {
          if (elements.length > 0) {
            const index = elements[0].index;
            setSelectedIndex(index);
          }
        },
        elements: {
          arc: {
            borderWidth: 0
          }
        }
      }
    };

    // Create chart instance
    chartInstance.current = new Chart(ctx, config);

    // Cleanup function
    return () => {
      if (chartInstance.current) {
        chartInstance.current.destroy();
      }
    };
  }, [data]);

  // Update colors when selectedIndex changes (without recreating chart)
  useEffect(() => {
    if (!chartInstance.current || !data || data.length === 0) return;

    const hasData = data && data.length > 0;
    const allValuesZero =
      hasData && data.every((item: any) => item.value === 0);

    if (allValuesZero) return; // No need to update colors for empty state

    // Update background colors without recreating the chart
    const selectedItem = data[selectedIndex];
    const isSelectedValueZero = selectedItem && selectedItem.value === 0;

    const newColors = data.map((_item: any, index: number) => {
      const baseColor =
        _item.value === 0
          ? "rgba(195, 193, 220, 0.3)"
          : COLOR_PALETTE[index % COLOR_PALETTE.length];

      if (index === selectedIndex) {
        // Use #FFC42F for selected segment if it has value
        // Otherwise use rgba(195, 193, 220, 0.3) for the entire ring
        return isSelectedValueZero ? "rgba(195, 193, 220, 0.3)" : "#FFC42F";
      }

      // If selected item has no value, make all segments the same color
      if (isSelectedValueZero) {
        return "rgba(195, 193, 220, 0.3)";
      }

      return baseColor;
    });

    // Update the chart colors directly
    chartInstance.current.data.datasets[0].backgroundColor = newColors;
    chartInstance.current.update("none"); // Update without animation
  }, [selectedIndex, data]);

  useEffect(() => {
    if (!volume || !data) return;
    const index = data.findIndex((item: any) => item.label === volume);

    if (index !== -1) {
      setSelectedIndex(index);
    }
  }, [volume, data]);

  // Calculate center record - show selected record
  const hasData = data && data.length > 0;
  const centerRecord = hasData
    ? data[selectedIndex] || data[0] || { value: 0, label: "0" }
    : { value: 0, label: "0" };

  return (
    <div className={clsx("relative w-full h-full", className)}>
      <canvas ref={chartRef} className="w-full h-full cursor-pointer" />

      {/* Center text content */}
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
        {formatLabel(centerRecord)}
      </div>
    </div>
  );
}
